### ISSUE TITLE
mongodb.url helper appears to ignore mongodb "standalone" configuration

### ISSUE THREAD

**Issue by derelbenkoenig** [wekan/charts#31]
I'm trying to deploy this chart into our Openshift at work using ArgoCD and seeing the pods crash loop back off with an error like this:
```
error: MongoNetworkError: getaddrinfo ENOTFOUND food-for-thought-wekan-stage-app-mongodb-2.food-for-thought-wekan-stage-app-mongodb
                        at connectionFailureError (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:387:20)
                        at Socket.<anonymous> (/build/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:310:22)
                        at Object.onceWrapper (events.js:520:26)
                        at Socket.emit (events.js:400:28)
                        at emitErrorNT (internal/streams/destroy.js:106:8)
                        at emitErrorCloseNT (internal/streams/destroy.js:74:3)
                        at processTicksAndRejections (internal/process/task_queues.js:82:21) {
                      cause: Error: getaddrinfo ENOTFOUND food-for-thought-wekan-stage-app-mongodb-2.food-for-thought-wekan-stage-app-mongodb
                          at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26) {
                        errno: -3008,
                        code: 'ENOTFOUND',
                        syscall: 'getaddrinfo',
                        hostname: 'food-for-thought-wekan-stage-app-mongodb-2.food-for-thought-wekan-stage-app-mongodb'
                      },
                      [Symbol(errorLabels)]: Set(1) { 'ResetPool' }
```

The `mongodb.url` section in `_helpers.tpl` looks like it only looks at `mongodb.replicaCount`, which according to the mongodb chart itself is ignored when the `mongodb.architecture` is set to `"standalone"`. So if setting the Mongo architecture to standalone, the `Deployment` ends up being created with a `MONGO_URL` environment variable that doesn't actually point to the MongoDB. I may be able to work around this by using the `replicaset` architecture but it feels like it may be overkill for my purposes.

**Comment by Yitter96** [comment]
Here is a solution to address the issue of generating the correct MongoDB URL for standalone mode in the Wekan Helm chart:

In the `_helpers.tpl` file, replace the existing `mongodb.url` definition:

```yaml
{{- define "mongodb.url" -}}
{{- if (index .Values "mongodb" "enabled") -}}
  {{- $count := (int (index .Values "mongodb" "replicaCount")) -}}
  {{- $release := .Release.Name -}}
  {{- $replicaSetName := (index .Values "mongodb" "replicaSetName") -}}
  {{- $mongodbSvcName := include "wekan.mongodb.svcname" . -}}
  mongodb://{{- range $v := until $count }}{{ $release }}-mongodb-{{ $v }}.{{ $mongodbSvcName }}:27017{{ if ne $v (sub $count 1) }},{{- end -}}{{- end -}}/{{ .Values.dbname }}
  {{- if gt $count 1 }}?replicaSet={{ $replicaSetName }}{{- end }}
{{- else -}}
  {{- index .Values "mongodb" "url" -}}
{{- end -}}
{{- end -}}
```

with this improved version:
```yaml
{{- define "mongodb.url" -}}
{{- if (index .Values "mongodb" "enabled") -}}
  {{- $count := (int (index .Values "mongodb" "replicaCount")) -}}
  {{- $release := .Release.Name -}}
  {{- $mongodbSvcName := include "wekan.mongodb.svcname" . -}}
  {{- if gt $count 1 -}}
    {{- $replicaSetName := (index .Values "mongodb" "replicaSetName") -}}
    mongodb://{{- range $v := until $count }}{{ $release }}-mongodb-{{ $v }}.{{ $mongodbSvcName }}:27017{{ if ne $v (sub $count 1) }},{{- end -}}{{- end -}}/{{ .Values.dbname }}?replicaSet={{ $replicaSetName }}
  {{- else -}}
    mongodb://{{ $release }}-mongodb-0.{{ $mongodbSvcName }}:27017/{{ .Values.dbname }}
  {{- end -}}
{{- else -}}
  {{- index .Values "mongodb" "url" -}}
{{- end -}}
{{- end -}}
```

This change ensures that the replicaSet parameter is only included when there is more than one replica, allowing standalone MongoDB configurations to work correctly.

**Comment by derelbenkoenig** [comment]
Nice, thanks
